sudo: required

language: java

services:
  - docker

jdk:
  - openjdk8

env:
  global:
    - secure: "Cex28W7Q/hefioXE3u5pdXlJOwyk0GPeO8+5XrAUvbZgfGDVfaGcEKjGE+qypQNBwrOmiiia/BKJjNAMxsKRytI8JGqvm12PWjctYP7u3Gt5eOKF4yNSZvrNF8aPtGEz4zeCLHsCIG0QIfqA8Kd+DuJBMyjALvwOiiq+2EJAJBPTIe/SzZ04rJpgwGj/TKlR2IUdKRLWI9B+a099dqSZt/S5DeOWxYfFjauxCXmgk/vK4kigO0DUYw3zZVBZMaDSzri+KVtYBVhlg55CsjiBTAHvsVH1e2hA0URh65M9jzmlW8pKIMromoWTzFUdvBhJNZwmCCi9mQi/ssffwbwEXGJ3V0eZ3QbQ7br+bzEPgLwQoCZTruILShpiGRBxERHSEt2kkpy8xhVBFWhSTgAfJUzT2HaJU0QO5coAH1YSXETKGC1zFCXdCp9xHvRZyigno794QMfQ6dv1/wlMOplpJwAcmT8zm71V2uNUS9rXzKVIh3Mxizge3kv/X696l2IFgIbDbD1mHwg4g+M26aCEgANfEYJJEdngBTlWIVnTveI52M1SUbCM7LUnjBBMa1ypSC20e6vx/0MXKosuRXYQQJvMQnwSVuAH6mBHoZOSWkopaF+dXKzT4hsyBg929fg+h8WLccl849gAlNlik9uYklPl0rtgh6JPr86+O6Rkn/Y="
    - # ^^ DOCKER_USERNAME
    - secure: "DYG+VKYxSpWpvOlqTYBseTRh2VwUqWrp3Dluowx6pVauCY49uvcMCibsg9TIicUwWBbRoW6Lf3CACbe43BsNDo0sPFvQEAAIPgDt8I9TMDpnF4RQbPI4x3MGPheTM1yi7CGtxnhVAs17Qw+OEKJj9Lf0L87orUZBQM9y5MMXixq0ZSbYH5BTtHoOHHmPD+2uVQsDXCDkRJ58CRgs6c0jpjuKzfRrdtJfKT0sNlpnN6v144ExWJEnIBscoz48kmMprSp4P/ehh88yolyxZOEt1NpcvWd2kWD2zEEpYeV0FHquyJwIEmObi7vZmfOUdPC0uUenT0PoQgEiCO162SqS8uH6zX+WOl9Hl/SCoWvuXqtZnsXT5X+WphrsXOmRO/Zz+9Fl9nwKAD8SItbk/Fgxa2F+Vv2ll9l1Sfkq/PFtAr/0UCMNdI3w5Bt9tW1B3Cu9MtPDB3jK/YQPFqbuTI1c6OeY7/o2JofJVWYSu9yAUto9shBJMmRHPrGpImkhLDS/lZh5a7ZUNm/cA9MKE6CNaUdI/qTaykZ3nWdrer/6AOevqW5H6J3fXtb68N/7iQHCthHyOEuCyyD9WzLNg52i62SlJanKh4EFh79GjuDzq3mObeXGjHLUkQWUpZkaKSi5weplfAniYTjhYCCKYCfzRUagEJS+VBZGKPYPrmW+ctk="
    - # ^^ DOCKER_PASSWORD

install:
  - mvn install -Dmaven.javadoc.skip=true

after_success:
  docker build -t netshoes/sample-sleuth-users:latest -t netshoes/sample-sleuth-users:1.0-SNAPSHOT .

deploy:
  provider: script
  script: bash src/main/bash/docker_push.sh
  on:
    branch: master

cache:
  directories:
    - ~/.m2/repository