sudo: required

language: java

services:
  - docker

jdk:
  - openjdk8

env:
  global:
    - secure: "FHi4hNisAvxWvEJ0a3jp+jgJNjIcHPoFMAHzC6ExoWwyXwQzkwGmIqN2ibl8KbsnR7UowurzGoCtBx7zrF24mpxk7lJ8LSZ2Im74i9Hv03kHpRumcSlw2gCdlBiWeK4slenIxDPdrT4IvyplWoknlD8oQEChqUfk/dqQUdl84JHDy/ISXIl3UlRRe7zGaca7f5Xf1ehXlZxrc616fIP8IP1aWRU9Gg4QKCx8UeVU75Or+NFCDumxZ4ov5dxqzcOnEaOc5V153RqwTRnYhW457PJzC2H8/Dg4lA2x5sFf4oClEzjg5890QLTPJVybhFaNOIPGGF7p0mZGLRX6T9IdgrHcRBbiSrudoKvPf9HH+E6EhgKXrzuzvdCdhFhlqHMd6bYvOZSNBp4hcS00R8dqO1Olct0tr4Hb42e5PTOQ5Bsr8J2FVn2RhO0BcbFttL1dMbkGF2mSykTNiiq9fqM2EbfJ4kzO3/mTzCA89CHjqo/3zAHfWwbVS48zrxXZ19OjFLtLNvgYWJwkJCKWGXcixuYbOIMXvUM0MY0sGbgeUj3EAi8Y1UQvEelAx/74bY+bpjXQePOFt6w1Ihe64KcDrvTP/q+EzhmiY0myD0+IM/EG22JLB0uHN8EUYpZCOhGmKsLNlXmRPHKc/8jN7nzkH0UkMZLSg5UOEhu2NwC/p9A="
    - # ^^ DOCKER_USERNAME
    - secure: "OGvYAp0bi2BZSWut5+SkO/lf1cwk1yNQ5gCgummBApoln81EFT988wO1WP3dmd/ba8TDe3WBQn2uCUqFp8rJH7QgfyzDNcbdyLn3i7A2LQRIs1N8aagZW/lr2/7jnP5Vd4Bp9adWZ3u3ZmLkEqHX9DYxmVJnVFK2lXtlGzUjx0EcoiopSuzfWnQLQc2BD9yKtEupMPFOCL3VnHNf5wNIVPrK5JukyEO/dW98NRoYozFkq3YW2kN7LheT88hOB0rXVs4/MxJYkpvvyowS2nLwBL4ixDWdJnQkcNM5DATxQPMsA6dL5JUWUpWfzjQdOmWDOUJCDZhQdYR+vBdeWDCzOfsl3nUfx47cUggvn2MUGyaE9bE8IrLMsqwwFqhe9XB7YY/oiaWMyI2XS4Poq1kvClbmS/1+ky9WpsP/a8PorU1YqJFXxBGlK+ivlheroYF8oEEujC47UhywijPbMGaRSfJvJF65S2XQ/sSWYcjSWfVCsdRU4kKJNIfKK11bX+VR8JaPk38zCHftjbAgK/V/Jey8W3wOnDtKkz9QiEwqNB136hJvwpn6qx3oi/ICVfpH360hp4xgdyXCKKr+VjVNrXScCjquF6B8vwh8CRO7F7aFl1QwkMVNP0Yrd+o4lhFNazY0jIok6fx783jJiPHXHRBx/ceFS8mAgVAjfJdNcFY="
    - # ^^ DOCKER_PASSWORD

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true

after_success:
  docker build . -t netshoes/sample-sleuth-users:1.0-SNAPSHOT

deploy:
  provider: script
  script: bash src/main/bash/docker_push.sh
  on:
    branch: master

cache:
  directories:
    - ~/.m2/repository